FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy source code
COPY src /app/src
COPY tests /app/tests
COPY jest.config.js /app/jest.config.js
COPY Makefile /app/Makefile

# Run tests
CMD ["npm", "run", "test:jest:coverage"]
